[package]
name = "myip"
version = "0.0.1"
authors = ["Ricthofen <jazzplato@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A simple command line tool to get the ip related information for your host."

[dependencies]
reqwest = "0.9.24"
